export const LAUNCHES_WITHOUT_FILTERS_REQUEST =
  "LAUNCHES_WITHOUT_FILTERS_REQUEST";
export const LAUNCHES_WITHOUT_FILTERS_SUCCESS =
  "LAUNCHES_WITHOUT_FILTERS_SUCCESS";
export const LAUNCHES_WITHOUT_FILTERS_ERROR = "LAUNCHES_WITHOUT_FILTERS_ERROR";

export const LAUNCHES_WITH_FILTERS_REQUEST = "LAUNCHES_WITH_FILTERS_REQUEST";
export const LAUNCHES_WITH_FILTERS_SUCCESS = "LAUNCHES_WITH_FILTERS_SUCCESS";
export const LAUNCHES_WITH_FILTERS_ERROR = "LAUNCHES_WITH_FILTERS_ERROR";
